### ISSUE TITLE
The latest version need a tag

### ISSUE THREAD

**Issue by ghost** [alann-maulana/flutter_hud#7]
Now, I have to do like the following method to use the latest version.

```
 flutter_hud:
    git:
      url: https://github.com/eyro-labs/flutter_hud.git
      ref: 9a10188d4f84939a5cd05170cd8bd081197fd596
```
